version: 2

tools:
  mix_credo: &mix_credo
    lint-command: "MIX_ENV=test mix credo suggest --format flycheck --ignore tagtodo --config-file ./data/.credo.exs --read-from-stdin ${INPUT}"
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %t: %m'
      - '%f:%l: %t: %m'
    lint-category-map:
      R: N
      D: I
      F: E
      W: W
      C: I
    root-markers:
      - mix.lock
      - mix.exs
    lint-ignore-exit-code: true

languages:
  elixir:
    - <<: *mix_credo

